
line-length = 88
target-version = "py310"

lint.select = [
    "A",  # prevent using keywords that clobber python builtins
    "B",  # bugbear: security warnings
    "E",  # pycodestyle
    "F",  # pyflakes
    "ISC",  # implicit string concatenation
    "UP",  # alert you when better syntax is available in your python version
    "RUF",  # the ruff developer's own rules
]

lint.ignore = [
    "B007", # Loop control variable `var` not used within loop body
    "E712",  # Allow using if x == False, as it's not always equivalent to if x.
    "E501",  # Supress line-too-long warnings: trust black's judgement on this one.
    "UP017",  # Allow timezone.utc instead of datetime.UTC.
    "ISC001", # Checks for implicitly concatenated strings on a single line.
    "RUF005", # Consider `[*list(impacts_std.values()), float("inf")]` instead of concatenation
]
